add_build_file_dep('//libs')
android_resource(
  name = 'res',
  res = 'snappy',
  package = 'com.whitedrop.snappy',
  deps = [
    '//libs:appcompat-v7',
    '//libs:design',
    '//libs:support-v4',
    '//libs:support-vector-drawable',
    '//libs:animated-vector-drawable',
    '//libs:recyclerview-v7',
    '//maven:com_facebook_fresco__drawee',
  ],
  visibility = [
    'PUBLIC',
  ]
)
project_config(
  src_target = '//res:res',
  src_roots = [ 'snappy' ]
)
