
android_resource(
  name = 'res',
  res = 'snappy',
  package = 'com.whitedrop.snappy',
  deps = [
    '//maven:com_android_support__animated-vector-drawable',
    '//maven:com_android_support__appcompat-v7',
    '//maven:com_android_support__design',
    '//maven:com_android_support__recyclerview-v7',
    '//maven:com_android_support__support-v13',
    '//maven:com_android_support__support-v4',
    '//maven:com_android_support__support-vector-drawable',
    '//maven:com_facebook_fresco__drawee',
  ],
  visibility = [
    'PUBLIC',
  ]
)
project_config(
  src_target = '//res:res',
  src_roots = [ 'snappy' ]
)
