add_build_file_dep('//libs')
android_resource(
  name = 'res',
  res = 'snappy',
  package = 'com.whitedrop.snappy',
  deps = get_deps([
    '//libs:appcompat-v7',
    '//libs:design',
    '//libs:support-v4',
    '//libs:support-vector-drawable',
    '//libs:animated-vector-drawable',
    '//libs:recyclerview-v7',
    '//mvn:com.facebook.fresco:drawee:0.11.0',
  ]),
  visibility = [
    'PUBLIC',
  ]
)
project_config(
  src_target = '//res:res',
  src_roots = [ 'snappy' ]
)
