add_build_file_dep('//libs')
project_config(
  src_target = '//java:main',
  src_roots = [ '.' ]
)
deps = [
  '//libs:appcompat-v7',
  '//libs:support-v4',
  '//libs:support-v13',
  '//libs:design',
  '//res:res',
  '//libs:recyclerview-v7',
  '//libs:greedo-layout',
  '//maven:com_facebook_fresco__fresco'
]
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(deps)
android_library(
  name = 'main',
  srcs = glob(['./**/*.java']),
  visibility = [ 'PUBLIC' ],
  deps = deps
)
