
android_prebuilt_aar(
  name = 'appcompat-v7',
  aar = 'appcompat-v7-23.4.0.aar',
  visibility = ['PUBLIC']
)
android_prebuilt_aar(
  name = 'design',
  aar = 'design-23.4.0.aar',
  visibility = ['PUBLIC']
)
